package SchoolStudent.core.SchoolLessonsAndCertificates;


import SchoolStudent.core.SchoolLessonsAndCertificates.dto.SaveStudentRequestForSchoolLessonsAndCertificatesMicroservice;
import SchoolStudent.core.SchoolLessonsAndCertificates.dto.SaveStudentResponseForSchoolLessonsAndCertificatesMicroservice;

public interface SchoolLessonsAndCertificatesMicroservice {

    SaveStudentResponseForSchoolLessonsAndCertificatesMicroservice execute(SaveStudentRequestForSchoolLessonsAndCertificatesMicroservice request);

}
