package SchoolStudent.core.SchoolLessonsAndCertificates.interficesForServices;

import SchoolStudent.core.SchoolLessonsAndCertificates.dto.request.GettingTheNameOfAnExistingLessonForSchoolLessonsAndCertificatesMicroserviceRequest;
import SchoolStudent.core.SchoolLessonsAndCertificates.dto.response.GettingTheNameOfAnExistingLessonForSchoolLessonsAndCertificatesMicroserviceResponse;

public interface SchoolLessonsAndCertificatesMicroserviceForGetSubjectNameService {

    GettingTheNameOfAnExistingLessonForSchoolLessonsAndCertificatesMicroserviceResponse execute(GettingTheNameOfAnExistingLessonForSchoolLessonsAndCertificatesMicroserviceRequest request);

}
