package SchoolStudent.core.SchoolLessonsAndCertificates.interficesForServices;


import SchoolStudent.core.SchoolLessonsAndCertificates.dto.request.SaveStudentForSchoolLessonsAndCertificatesMicroserviceRequest;
import SchoolStudent.core.SchoolLessonsAndCertificates.dto.request.TransferOfStudentToANewClassForSchoolLessonsAndCertificatesMicroserviceRequest;
import SchoolStudent.core.SchoolLessonsAndCertificates.dto.response.SaveStudentForSchoolLessonsAndCertificatesMicroserviceResponse;
import SchoolStudent.core.SchoolLessonsAndCertificates.dto.response.TransferStudentToANewClassForSchoolLessonsAndCertificatesMicroserviceResponse;

public interface SchoolLessonsAndCertificatesMicroserviceForTransferStudent {

    TransferStudentToANewClassForSchoolLessonsAndCertificatesMicroserviceResponse execute(TransferOfStudentToANewClassForSchoolLessonsAndCertificatesMicroserviceRequest request);

}
